-- ============================================================================
-- TABLES: checkpoints, checkpoint_blobs, checkpoint_writes, checkpoint_migrations
-- ============================================================================
-- ⚠️  IMPORTANT: These tables are AUTO-GENERATED by LangGraph's
--     AsyncPostgresSaver / PostgresSaver when it initializes the database.
--     They are NOT part of the application's business schema.
--
--     DO NOT modify these tables manually. LangGraph manages their schema
--     and data lifecycle. They are documented here for reference only.
--
-- Source: Extracted directly from the live Supabase database.
-- ============================================================================

-- ── checkpoints ──────────────────────────────────────────────────────────────
-- Stores LangGraph conversation checkpoints (state snapshots).

CREATE TABLE IF NOT EXISTS public.checkpoints (
    thread_id           text                        NOT NULL,
    checkpoint_ns       text                        NOT NULL DEFAULT ''::text,
    checkpoint_id       text                        NOT NULL,
    parent_checkpoint_id text,
    type                text,
    checkpoint          jsonb                       NOT NULL,
    metadata            jsonb                       NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT checkpoints_pkey PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
);

CREATE INDEX IF NOT EXISTS checkpoints_thread_id_idx
    ON public.checkpoints USING btree (thread_id);

-- ── checkpoint_blobs ─────────────────────────────────────────────────────────
-- Stores binary blobs associated with checkpoints (large state values).

CREATE TABLE IF NOT EXISTS public.checkpoint_blobs (
    thread_id           text                        NOT NULL,
    checkpoint_ns       text                        NOT NULL DEFAULT ''::text,
    channel             text                        NOT NULL,
    version             text                        NOT NULL,
    type                text                        NOT NULL,
    blob                bytea,

    CONSTRAINT checkpoint_blobs_pkey PRIMARY KEY (thread_id, checkpoint_ns, channel, version)
);

CREATE INDEX IF NOT EXISTS checkpoint_blobs_thread_id_idx
    ON public.checkpoint_blobs USING btree (thread_id);

-- ── checkpoint_writes ────────────────────────────────────────────────────────
-- Stores pending writes for checkpoint recovery and state updates.

CREATE TABLE IF NOT EXISTS public.checkpoint_writes (
    thread_id           text                        NOT NULL,
    checkpoint_ns       text                        NOT NULL DEFAULT ''::text,
    checkpoint_id       text                        NOT NULL,
    task_id             text                        NOT NULL,
    idx                 integer                     NOT NULL,
    channel             text                        NOT NULL,
    type                text,
    blob                bytea                       NOT NULL,
    task_path           text                        NOT NULL DEFAULT ''::text,

    CONSTRAINT checkpoint_writes_pkey PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)
);

CREATE INDEX IF NOT EXISTS checkpoint_writes_thread_id_idx
    ON public.checkpoint_writes USING btree (thread_id);

-- ── checkpoint_migrations ────────────────────────────────────────────────────
-- Tracks LangGraph checkpoint schema migrations.

CREATE TABLE IF NOT EXISTS public.checkpoint_migrations (
    v                   integer                     NOT NULL,

    CONSTRAINT checkpoint_migrations_pkey PRIMARY KEY (v)
);

-- ── NOTE ─────────────────────────────────────────────────────────────────────
-- RLS is intentionally DISABLED on checkpoint tables because:
-- 1. They are managed by LangGraph's AsyncPostgresSaver using the service_role key
-- 2. Access control is handled at the application level (thread_id scoping)
-- 3. Enabling RLS would break LangGraph's checkpoint read/write operations
